"""Cross-asset and portfolio-level analysis utilities."""

from rde.analysis.cross_asset import (
    AssetRegimeData,
    CrossAssetResult,
    compute_cross_asset,
    load_asset_regime_data,
)
from rde.analysis.portfolio import (
    AllocationConfig,
    KellyConfig,
    VolTargetConfig,
    kelly_weights,
    portfolio_returns,
    score_proportional_weights,
    vol_target_weights,
)
from rde.analysis.regime_var import (
    RegimeVARConfig,
    RegimeVARResult,
    compute_irf,
    fit_regime_var,
    granger_causality_table,
)
from rde.analysis.drawdown_control import (
    DrawdownControlConfig,
    RegimePositionLimitConfig,
    apply_drawdown_control,
    apply_regime_position_limits,
    drawdown_scale_factor,
    regime_drawdown_budget,
    regime_position_limits,
    running_drawdown,
)
from rde.analysis.information_geometry import (
    DistinguishabilityResult,
    bhattacharyya_coefficient,
    bhattacharyya_distance,
    compute_distinguishability,
    js_divergence_gaussians,
    kl_divergence_gaussians,
    mahalanobis_distance,
    markov_entropy_rate,
    regime_entropy,
)
from rde.analysis.risk_metrics import (
    RegimeRiskConfig,
    RegimeRiskResult,
    compute_regime_risk,
    compute_regime_risk_weighted,
    regime_risk_divergence,
)
from rde.analysis.correlation import (
    CorrelationConfig,
    RegimeCorrelation,
    RegimeCorrelationResult,
    correlation_breakdown,
    dynamic_conditional_correlation,
    regime_correlation,
    tail_dependence,
)
from rde.analysis.backtest import (
    BacktestResult,
    RegimeRule,
    RegimeStrategyConfig,
    backtest_tearsheet,
    regime_performance_attribution,
    run_backtest,
)
from rde.analysis.tail_risk import (
    GPDParams,
    RegimeTailResult,
    TailConfig,
    fit_gpd,
    fit_regime_tails,
    gpd_es,
    gpd_var,
    stress_test_scenarios,
    tail_risk_decomposition,
)
from rde.analysis.transition_prediction import (
    RegimeTransitionPredictor,
    TransitionPredictorConfig,
    blend_hmm_logistic,
    expected_regime_duration,
    multi_step_transition,
    persistence_forecast,
    transition_entropy_trajectory,
)
from rde.analysis.signal_filtering import (
    EMAConfig,
    HPConfig,
    KalmanSmootherConfig,
    adaptive_kalman_smoother,
    composite_signal,
    regime_ema,
    regime_hp_filter,
)
from rde.analysis.portfolio_optimization import (
    EfficientFrontier,
    MVOConfig,
    RegimeMVOResult,
    RegimeMVOWeights,
    black_litterman_posterior,
    blended_mvo,
    efficient_frontier,
    regime_mvo,
)
from rde.analysis.cointegration import (
    RegimeCointegrationResult,
    RegimeSpreadParams,
    SpreadConfig,
    fit_regime_spreads,
    half_life_ornstein_uhlenbeck,
    regime_half_lives,
    regime_spread_zscore,
    spread_zscore,
    weighted_ols,
)
from rde.analysis.factor_analysis import (
    FactorConfig,
    RegimeFactorResult,
    RegimeFactors,
    factor_alignment,
    factor_return_decomposition,
    fit_regime_factors,
    project_to_factors,
    rolling_factor_exposure,
)
from rde.analysis.execution import (
    ExecutionConfig,
    ImpactModelConfig,
    OrderSchedule,
    RegimeImpactParams,
    estimate_regime_impact,
    expected_slippage,
    optimal_order_schedule,
    slippage_attribution,
    twap_schedule,
    vwap_schedule,
)

from rde.analysis.pipeline import (
    AnalysisConfig,
    AnalysisPipeline,
    AnalysisReport,
)
from rde.analysis.reporting import (
    report_to_dict,
    report_to_json,
    report_to_markdown,
    save_report,
)
from rde.analysis.regime_concordance import (
    ConcordanceConfig,
    ConcordanceResult,
    PairwiseConcordance,
    compute_concordance,
    concordance_heatmap_data,
    rolling_concordance_series,
)
from rde.analysis.multi_asset_allocation import (
    MultiAssetConfig,
    MultiAssetResult,
    collect_rtmv_rebalance_cache,
    compare_allocations,
    compute_rtmv_weights_now,
    equal_weight_baseline,
    global_min_var_baseline,
    regime_informed_min_var,
    regime_tilted_min_var,
    regime_tilted_min_var_from_cache,
    run_multi_asset_allocation,
)

__all__ = [
    # cross-asset
    "AssetRegimeData",
    "CrossAssetResult",
    "compute_cross_asset",
    "load_asset_regime_data",
    # portfolio
    "AllocationConfig",
    "KellyConfig",
    "VolTargetConfig",
    "kelly_weights",
    "portfolio_returns",
    "score_proportional_weights",
    "vol_target_weights",
    # regime VAR
    "RegimeVARConfig",
    "RegimeVARResult",
    "fit_regime_var",
    "compute_irf",
    "granger_causality_table",
    # drawdown control
    "DrawdownControlConfig",
    "RegimePositionLimitConfig",
    "running_drawdown",
    "drawdown_scale_factor",
    "apply_drawdown_control",
    "regime_position_limits",
    "apply_regime_position_limits",
    "regime_drawdown_budget",
    # information geometry
    "DistinguishabilityResult",
    "kl_divergence_gaussians",
    "js_divergence_gaussians",
    "bhattacharyya_distance",
    "bhattacharyya_coefficient",
    "mahalanobis_distance",
    "markov_entropy_rate",
    "regime_entropy",
    "compute_distinguishability",
    # risk metrics
    "RegimeRiskConfig",
    "RegimeRiskResult",
    "compute_regime_risk",
    "compute_regime_risk_weighted",
    "regime_risk_divergence",
    # correlation / dependence
    "CorrelationConfig",
    "RegimeCorrelation",
    "RegimeCorrelationResult",
    "regime_correlation",
    "dynamic_conditional_correlation",
    "tail_dependence",
    "correlation_breakdown",
    # backtesting
    "RegimeRule",
    "RegimeStrategyConfig",
    "BacktestResult",
    "run_backtest",
    "regime_performance_attribution",
    "backtest_tearsheet",
    # tail risk / EVT
    "TailConfig",
    "GPDParams",
    "RegimeTailResult",
    "fit_gpd",
    "gpd_var",
    "gpd_es",
    "fit_regime_tails",
    "tail_risk_decomposition",
    "stress_test_scenarios",
    # transition prediction
    "TransitionPredictorConfig",
    "RegimeTransitionPredictor",
    "multi_step_transition",
    "persistence_forecast",
    "expected_regime_duration",
    "blend_hmm_logistic",
    "transition_entropy_trajectory",
    # signal filtering
    "EMAConfig",
    "HPConfig",
    "KalmanSmootherConfig",
    "regime_ema",
    "regime_hp_filter",
    "adaptive_kalman_smoother",
    "composite_signal",
    # portfolio optimization
    "MVOConfig",
    "RegimeMVOWeights",
    "RegimeMVOResult",
    "EfficientFrontier",
    "regime_mvo",
    "blended_mvo",
    "efficient_frontier",
    "black_litterman_posterior",
    # cointegration / spread
    "SpreadConfig",
    "RegimeSpreadParams",
    "RegimeCointegrationResult",
    "weighted_ols",
    "half_life_ornstein_uhlenbeck",
    "fit_regime_spreads",
    "spread_zscore",
    "regime_spread_zscore",
    "regime_half_lives",
    # factor analysis
    "FactorConfig",
    "RegimeFactors",
    "RegimeFactorResult",
    "fit_regime_factors",
    "factor_alignment",
    "rolling_factor_exposure",
    "project_to_factors",
    "factor_return_decomposition",
    # execution
    "ImpactModelConfig",
    "ExecutionConfig",
    "RegimeImpactParams",
    "OrderSchedule",
    "estimate_regime_impact",
    "expected_slippage",
    "optimal_order_schedule",
    "twap_schedule",
    "vwap_schedule",
    "slippage_attribution",
    # Phase 31 — analysis pipeline + reporting
    "AnalysisConfig",
    "AnalysisPipeline",
    "AnalysisReport",
    "report_to_dict",
    "report_to_json",
    "report_to_markdown",
    "save_report",
    # Phase 34 — regime concordance
    "ConcordanceConfig",
    "ConcordanceResult",
    "PairwiseConcordance",
    "compute_concordance",
    "concordance_heatmap_data",
    "rolling_concordance_series",
    # Phase 42 — multi-asset regime allocation
    "MultiAssetConfig",
    "MultiAssetResult",
    "run_multi_asset_allocation",
    "regime_informed_min_var",
    "regime_tilted_min_var",
    "collect_rtmv_rebalance_cache",
    "regime_tilted_min_var_from_cache",
    "equal_weight_baseline",
    "global_min_var_baseline",
    "compare_allocations",
    # Phase 48 — live weight computation
    "compute_rtmv_weights_now",
]
